//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reclamacion()
        {
            this.Respuesta_Empleado = new HashSet<Respuesta_Empleado>();
            this.Respuesta_Cliente = new HashSet<Respuesta_Cliente>();
        }
    
        public int ID_Reclamacion { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public string Id_UserName { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> ID_Departamento { get; set; }
        public Nullable<int> ID_Tipo_Reclamacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> ID_Estado_QR { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> ID_Sucursal { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado_QR Estado_QR { get; set; }
        public virtual Tipo_Reclamacion Tipo_Reclamacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_Empleado> Respuesta_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_Cliente> Respuesta_Cliente { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
