//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Transaccion_Producto
    {
        public int ID_Transaccion { get; set; }
        public int ID_Producto { get; set; }
        public Nullable<int> Cantidad_Producto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
