//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_Cliente
    {
        public int ID_Respuesta_Cliente { get; set; }
        public Nullable<int> Id_Queja { get; set; }
        public Nullable<int> Id_Reclamacion { get; set; }
        public Nullable<int> ID_Estado_Origen { get; set; }
        public Nullable<int> ID_Estado_Destino { get; set; }
        public Nullable<int> Valoracion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
    
        public virtual Estado_QR Estado_QR { get; set; }
        public virtual Estado_QR Estado_QR1 { get; set; }
        public virtual Queja Queja { get; set; }
        public virtual Reclamacion Reclamacion { get; set; }
    }
}
