//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Rel_Transaccion_Producto = new HashSet<Rel_Transaccion_Producto>();
        }
    
        public int ID_Transaccion { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ID_Estado_Transaccion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado_Transaccion Estado_Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_Transaccion_Producto> Rel_Transaccion_Producto { get; set; }
    }
}
